// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Proyecto_TFM_2

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void AnimationMotorAscendente_Animation(lv_obj_t * TargetObject, int delay);
void AnimationMotorDescendiente_Animation(lv_obj_t * TargetObject, int delay);

// Gráficos de series de datos de los encoders
lv_chart_series_t * ui_GraphEncoder_series_1 = NULL;
lv_chart_series_t * ui_GraphEncoder_series_2 = NULL;

lv_chart_series_t * ui_GraphEncoder3_series_1 = NULL; // Horizontal (rojo)
lv_chart_series_t * ui_GraphEncoder3_series_2 = NULL; // Vertical (azul)

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Image1;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label2;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label5;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Label11;
void ui_event_Button18(lv_event_t * e);
lv_obj_t * ui_Button18;
lv_obj_t * ui_Label25;
void ui_event_ControlDeBrillo(lv_event_t * e);
lv_obj_t * ui_ControlDeBrillo;
lv_obj_t * ui_ImagenControlDeBrillo;
// CUSTOM VARIABLES
lv_obj_t * uic_ImagenControlDeBrillo;

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
void ui_event_Button9(lv_event_t * e);
lv_obj_t * ui_Button9;
lv_obj_t * ui_Label16;
void ui_event_Button10(lv_event_t * e);
lv_obj_t * ui_Button10;
lv_obj_t * ui_Label17;
void ui_event_Button11(lv_event_t * e);
lv_obj_t * ui_Button11;
lv_obj_t * ui_Label18;
void ui_event_Button12(lv_event_t * e);
lv_obj_t * ui_Button12;
lv_obj_t * ui_Label19;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label15;
// CUSTOM VARIABLES


// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Kpvv;
lv_obj_t * ui_Kpvh;
lv_obj_t * ui_Kivv;
lv_obj_t * ui_Kivh;
lv_obj_t * ui_Kdvv;
lv_obj_t * ui_Kdvh;
lv_obj_t * ui_Kphv;
lv_obj_t * ui_Kihh;
lv_obj_t * ui_Kihv;
lv_obj_t * ui_Kphh;
lv_obj_t * ui_Isatvv;
lv_obj_t * ui_Kdhh;
lv_obj_t * ui_Kdhv;
lv_obj_t * ui_Uvmax;
lv_obj_t * ui_Isathh;
lv_obj_t * ui_Isathv;
lv_obj_t * ui_Isatvh;
lv_obj_t * ui_Uhmax;
void ui_event_Button13(lv_event_t * e);
lv_obj_t * ui_Button13;
lv_obj_t * ui_Label57;
void ui_event_Button14(lv_event_t * e);
lv_obj_t * ui_Button14;
lv_obj_t * ui_Label20;
void ui_event_SliderKpvv(lv_event_t * e);
lv_obj_t * ui_SliderKpvv;
void ui_event_SliderKivv(lv_event_t * e);
lv_obj_t * ui_SliderKivv;
void ui_event_SliderKdvh(lv_event_t * e);
lv_obj_t * ui_SliderKdvh;
void ui_event_SliderKdvv(lv_event_t * e);
lv_obj_t * ui_SliderKdvv;
void ui_event_SliderKivh(lv_event_t * e);
lv_obj_t * ui_SliderKivh;
void ui_event_SliderKpvh(lv_event_t * e);
lv_obj_t * ui_SliderKpvh;
void ui_event_SliderKihv(lv_event_t * e);
lv_obj_t * ui_SliderKihv;
void ui_event_SliderKphv(lv_event_t * e);
lv_obj_t * ui_SliderKphv;
void ui_event_SliderKihh(lv_event_t * e);
lv_obj_t * ui_SliderKihh;
void ui_event_SliderKphh(lv_event_t * e);
lv_obj_t * ui_SliderKphh;
void ui_event_SliderKdhv(lv_event_t * e);
lv_obj_t * ui_SliderKdhv;
void ui_event_SliderKdhh(lv_event_t * e);
lv_obj_t * ui_SliderKdhh;
void ui_event_SliderIsatvv(lv_event_t * e);
lv_obj_t * ui_SliderIsatvv;
void ui_event_SliderIsatvh(lv_event_t * e);
lv_obj_t * ui_SliderIsatvh;
void ui_event_SliderIsathv(lv_event_t * e);
lv_obj_t * ui_SliderIsathv;
void ui_event_SliderIsathh(lv_event_t * e);
lv_obj_t * ui_SliderIsathh;
void ui_event_SliderUvmax(lv_event_t * e);
lv_obj_t * ui_SliderUvmax;
void ui_event_SliderUhmax(lv_event_t * e);
lv_obj_t * ui_SliderUhmax;
lv_obj_t * ui_Label82;
void ui_event_Button25(lv_event_t * e);
lv_obj_t * ui_Button25;
lv_obj_t * ui_Label34;
void ui_event_Button21(lv_event_t * e);
lv_obj_t * ui_Button21;
lv_obj_t * ui_Label38;
lv_obj_t * ui_Label36;
// CUSTOM VARIABLES


// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
lv_obj_t * ui_Screen5;
void ui_event_Button15(lv_event_t * e);
lv_obj_t * ui_Button15;
void ui_event_Label58(lv_event_t * e);
lv_obj_t * ui_Label58;
lv_obj_t * ui_Label59;
lv_obj_t * ui_EsquemaTRMSCompleto;
lv_obj_t * ui_EsquemaGeneral;
lv_obj_t * ui_EsquemaPIDCompleto;
// CUSTOM VARIABLES


// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
lv_obj_t * ui_Screen6;
void ui_event_Button17(lv_event_t * e);
lv_obj_t * ui_Button17;
lv_obj_t * ui_Label61;
lv_obj_t * ui_Label64;
lv_obj_t * ui_Label65;
lv_obj_t * ui_V_rotor_2;
void ui_event_Button16(lv_event_t * e);
lv_obj_t * ui_Button16;
lv_obj_t * ui_Label72;
lv_obj_t * ui_V_motor_principal_2;
lv_obj_t * ui_GraphEncoder3;
void ui_event_Button26(lv_event_t * e);
lv_obj_t * ui_Button26;
lv_obj_t * ui_Label39;
lv_obj_t * ui_Image12;
// CUSTOM VARIABLES


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label3;
void ui_event_RotorDeCola(lv_event_t * e);
lv_obj_t * ui_RotorDeCola;
void ui_event_MotorPrincipal(lv_event_t * e);
lv_obj_t * ui_MotorPrincipal;
lv_obj_t * ui_EstructuraMotores;
lv_obj_t * ui_EstructuraPrincipal;
lv_obj_t * ui_FlechaVerdeRecta;
lv_obj_t * ui_FlechaVerdeRectaGirada;
lv_obj_t * ui_FlechaVerdeCurva;
lv_obj_t * ui_FlechaVerdeCurvaGirada;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label4;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
lv_obj_t * ui_Label10;
void ui_event_Button8(lv_event_t * e);
lv_obj_t * ui_Button8;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_V_rotor_1;
lv_obj_t * ui_V_motor_principal_1;
lv_obj_t * ui_GraphEncoder;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label80;
lv_obj_t * ui_VinRDC;
lv_obj_t * ui_VinMP;
lv_obj_t * ui_Label43;
// CUSTOM VARIABLES
lv_obj_t * uic_Slider3;


// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
lv_obj_t * ui_Screen7;
lv_obj_t * ui_Label83;
void ui_event_Config4(lv_event_t * e);
lv_obj_t * ui_Config4;
void ui_event_Config3(lv_event_t * e);
lv_obj_t * ui_Config3;
void ui_event_Config2(lv_event_t * e);
lv_obj_t * ui_Config2;
void ui_event_Config1(lv_event_t * e);
lv_obj_t * ui_Config1;
void ui_event_SaveEEPROM(lv_event_t * e);
lv_obj_t * ui_SaveEEPROM;
void ui_event_Button20(lv_event_t * e);
lv_obj_t * ui_Button20;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label92;
// CUSTOM VARIABLES


// SCREEN: ui_Screen8
void ui_Screen8_screen_init(void);
lv_obj_t * ui_Screen8;
lv_obj_t * ui_Label24;
void ui_event_Button22(lv_event_t * e);
lv_obj_t * ui_Button22;
lv_obj_t * ui_Label26;
void ui_event_Label30(lv_event_t * e);
lv_obj_t * ui_Label30;
void ui_event_Label31(lv_event_t * e);
lv_obj_t * ui_Label31;
void ui_event_Label32(lv_event_t * e);
lv_obj_t * ui_Label32;
void ui_event_Label33(lv_event_t * e);
lv_obj_t * ui_Label33;
lv_obj_t * ui_Label37;
void ui_event_Label28(lv_event_t * e);
lv_obj_t * ui_Label28;
void ui_event_Label35(lv_event_t * e);
lv_obj_t * ui_Label35;
// CUSTOM VARIABLES


// SCREEN: ui_Screen10
void ui_Screen10_screen_init(void);
void ui_event_Screen10(lv_event_t * e);
lv_obj_t * ui_Screen10;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Image6;
// CUSTOM VARIABLES


// SCREEN: ui_Screen9
void ui_Screen9_screen_init(void);
lv_obj_t * ui_Screen9;
lv_obj_t * ui_Label27;
void ui_event_Button23(lv_event_t * e);
lv_obj_t * ui_Button23;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Image7;
lv_obj_t * ui_ButtonSelected;
void ui_event_Button19(lv_event_t * e);
lv_obj_t * ui_Button19;
lv_obj_t * ui_Label21;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_base_y_estructura_principal_x[1] = {&ui_img_base_y_estructura_principal_150x150_png};
const lv_img_dsc_t * ui_imgset_flecha_verde_curvada_x[1] = {&ui_img_flecha_verde_curvada_50x50_png};
const lv_img_dsc_t * ui_imgset_flecha_verde_invertida_x[1] = {&ui_img_flecha_verde_invertida_50x50_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void AnimationMotorAscendente_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, -90);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle);
    lv_anim_start(&PropertyAnimation_0);

}
void AnimationMotorDescendiente_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 90);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////

void ui_event_ControlDeBrillo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        function_Brightness_Control(e);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        Initiate_Modo_Manual(e);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        Initiate_Control_PID(e);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen8_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        function_Program_Select(e);
    }
}

void ui_event_Button18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen9, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen9_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        function_IR_Config(e);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        function_Init_1(e);
    }
}

void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen4_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        function_PID_Parameters_Config(e);
    }
}

void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen7_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        function_Load_Parameters_From_SD(e);
    }
}

void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen6_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        function_Start_Control_PID(e);
    }
}

void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        function_Reset_Encoders_And_Registers(e);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen5_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        function_General_Diagram_Model(e);
    }
}

void ui_event_Button13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        function_Control_PID_Menu(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        function_Predeterminate_parameters(e);
    }
}

void ui_event_SliderKpvv(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        function_Kpvv(e);
    }
}

void ui_event_SliderKivv(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        function_Kivv(e);
    }
}

void ui_event_SliderKdvh(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        function_Kdvh(e);
    }
}

void ui_event_SliderKdvv(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        function_Kdvv(e);
    }
}

void ui_event_SliderKivh(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        function_Kivh(e);
    }
}

void ui_event_SliderKpvh(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        function_Kpvh(e);
    }
}

void ui_event_SliderKihv(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        function_Kihv(e);
    }
}

void ui_event_SliderKphv(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        function_Kphv(e);
    }
}

void ui_event_SliderKihh(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        function_Kihh(e);
    }
}

void ui_event_SliderKphh(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        function_Kphh(e);
    }
}

void ui_event_SliderKdhv(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        function_Kdhv(e);
    }
}

void ui_event_SliderKdhh(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        function_Kdhh(e);
    }
}

void ui_event_SliderIsatvv(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        function_Isatvv(e);
    }
}

void ui_event_SliderIsatvh(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        function_Isatvh(e);
    }
}

void ui_event_SliderIsathv(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        function_Isathv(e);
    }
}

void ui_event_SliderIsathh(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        function_Isathh(e);
    }
}

void ui_event_SliderUvmax(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        function_Uvmax(e);
    }
}

void ui_event_SliderUhmax(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        function_Uhmax(e);
    }
}

void ui_event_Button25(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        function_Save_Config_1(e);
    }
}

void ui_event_Button21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        function_Save_Config_2(e);
    }
}

void ui_event_Button15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        function_Change_Images(e);
    }
}

void ui_event_Label58(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_Button17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        function_Control_PID_Menu_1(e);
    }
}

void ui_event_Button16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        function_Encoders_2(e);
    }
}

void ui_event_Button26(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        function_Angle_Reset(e);
    }
}

void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Encoders_GraphicModel(e);
    }
}

void ui_event_RotorDeCola(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        F_Rotor_De_Cola(e);
    }
}

void ui_event_MotorPrincipal(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        F_Motor_Principal(e);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        function_Init(e);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        function_Encoders_GraphModel(e);
    }
}

void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        function_Reset_Encoders_And_Registers(e);
    }
}

void ui_event_Config4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        function_Load_Config_4(e);
    }
}

void ui_event_Config3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        function_Load_Config_3(e);
    }
}

void ui_event_Config2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        function_Load_Config_2(e);
    }
}

void ui_event_Config1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        function_Load_Config_1(e);
    }
}

void ui_event_SaveEEPROM(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        function_Save_Config_In_EEPROM(e);
    }
}

void ui_event_Button20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        function_Control_PID_Menu_2(e);
    }
}

void ui_event_Button22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        function_Init_2(e);
    }
}

void ui_event_Label30(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        function_Program_4(e);
    }
}

void ui_event_Label31(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        function_Program_3(e);
    }
}

void ui_event_Label32(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        function_Program_2(e);
    }
}

void ui_event_Label33(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        function_Program_1(e);
    }
}

void ui_event_Label28(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        function_Program_4(e);
    }
}

void ui_event_Label35(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        function_Program_5(e);
    }
}

void ui_event_Screen10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        function_Salvapantallas(e);
    }
}

void ui_event_Button23(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        function_Init_3(e);
    }
}

void ui_event_Button19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        function_Save_Button_Config(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui_Screen5_screen_init();
    ui_Screen6_screen_init();
    ui_Screen2_screen_init();
    ui_Screen7_screen_init();
    ui_Screen8_screen_init();
    ui_Screen10_screen_init();
    ui_Screen9_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
