// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Proyecto_TFM_2

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

//Pines de LED y Buzzer
#define LED 33
#define Buzzer 27

// Pines y macros  para control del brillo de la pantalla (solo funciona cuando el jumper 
// está conectado correctamente)
#define BRILLO_PIN 3
#define BRILLO_PWM_CHANNEL  0
#define BRILLO_PWM_FREQ     5000   // 5 kHz (perfecto para backlight)
#define BRILLO_PWM_RES      8      // 8 bits -> 0..255


// Declaraciones globales
extern int Registro_MP;
extern int Registro_RDC;
extern float temp_Save_Message;
extern float temp_Load_Message;

void F_Rotor_Derecha(lv_event_t * e);
void F_Rotor_Izquierda(lv_event_t * e);
void F_Motor_Ascendente(lv_event_t * e);
void F_Motor_Descendente(lv_event_t * e);
void Reset_Encoders_Registros();
void Show_Save_Message_Selected();
void Show_Config_Message_Selected();
void BuzzerWrite(bool level);
void brightness_Control();

void Initiate_Modo_Manual(lv_event_t * e);
void Initiate_Control_PID(lv_event_t * e);
void function_Program_Select(lv_event_t * e);
void function_IR_Config(lv_event_t * e);
void function_Brightness_Control(lv_event_t * e);
void function_Init_1(lv_event_t * e);
void function_PID_Parameters_Config(lv_event_t * e);
void function_Load_Parameters_From_SD(lv_event_t * e);
void function_Start_Control_PID(lv_event_t * e);
void function_Reset_Encoders_And_Registers(lv_event_t * e);
void function_General_Diagram_Model(lv_event_t * e);
void function_Control_PID_Menu(lv_event_t * e);
void function_Predeterminate_parameters(lv_event_t * e);
void function_Kpvv(lv_event_t * e);
void function_Kivv(lv_event_t * e);
void function_Kdvh(lv_event_t * e);
void function_Kdvv(lv_event_t * e);
void function_Kivh(lv_event_t * e);
void function_Kpvh(lv_event_t * e);
void function_Kihv(lv_event_t * e);
void function_Kphv(lv_event_t * e);
void function_Kihh(lv_event_t * e);
void function_Kphh(lv_event_t * e);
void function_Kdhv(lv_event_t * e);
void function_Kdhh(lv_event_t * e);
void function_Isatvv(lv_event_t * e);
void function_Isatvh(lv_event_t * e);
void function_Isathv(lv_event_t * e);
void function_Isathh(lv_event_t * e);
void function_Uvmax(lv_event_t * e);
void function_Uhmax(lv_event_t * e);
void function_Save_Config_1(lv_event_t * e);
void function_Save_Config_2(lv_event_t * e);
void function_Change_Images(lv_event_t * e);
void function_Control_PID_Menu_1(lv_event_t * e);
void function_Encoders_2(lv_event_t * e);
void function_Angle_Reset(lv_event_t * e);
void Encoders_GraphicModel(lv_event_t * e);
void F_Rotor_De_Cola(lv_event_t * e);
void F_Motor_Principal(lv_event_t * e);
void function_Init(lv_event_t * e);
void function_Encoders_GraphModel(lv_event_t * e);
void function_Load_Config_4(lv_event_t * e);
void function_Load_Config_3(lv_event_t * e);
void function_Load_Config_2(lv_event_t * e);
void function_Load_Config_1(lv_event_t * e);
void function_Save_Config_In_EEPROM(lv_event_t * e);
void function_Control_PID_Menu_2(lv_event_t * e);
void function_Init_2(lv_event_t * e);
void function_Program_5(lv_event_t * e);
void function_Program_4(lv_event_t * e);
void function_Program_3(lv_event_t * e);
void function_Program_2(lv_event_t * e);
void function_Program_1(lv_event_t * e);
void function_Salvapantallas(lv_event_t * e);
void function_Init_3(lv_event_t * e);
void function_Save_Button_Config(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
