// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Proyecto_TFM_2

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_Screen1);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 148
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 139
    lv_obj_set_x(ui_Image3, -986);
    lv_obj_set_y(ui_Image3, -94);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_reposo_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 205
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 170
    lv_obj_set_x(ui_Image1, -121);
    lv_obj_set_y(ui_Image1, -60);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 111);
    lv_obj_set_height(ui_Button1, 60);
    lv_obj_set_x(ui_Button1, 57);
    lv_obj_set_y(ui_Button1, -90);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Modo manual");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Montserrat_14_Latin_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button4, 111);
    lv_obj_set_height(ui_Button4, 60);
    lv_obj_set_x(ui_Button4, 56);
    lv_obj_set_y(ui_Button4, -20);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Modo Go to \n      Goal");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Montserrat_14_Latin_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button3, 108);
    lv_obj_set_height(ui_Button3, 60);
    lv_obj_set_x(ui_Button3, 178);
    lv_obj_set_y(ui_Button3, -90);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -1);
    lv_obj_set_y(ui_Label8, -1);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Seleccionar \n  programa");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_Montserrat_14_Latin_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_logo_ugr_redimensionado_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 120
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_x(ui_Image2, -123);
    lv_obj_set_y(ui_Image2, 92);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image4, &ui_img_logo_granasat_redimensionado_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 120
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_x(ui_Image4, 9);
    lv_obj_set_y(ui_Image4, 94);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel4, 120);
    lv_obj_set_height(ui_Panel4, 120);
    lv_obj_set_x(ui_Panel4, 141);
    lv_obj_set_y(ui_Panel4, 92);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Hardware\n	   V 1.0\nFirmware\n     V 2.0");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button18 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button18, 110);
    lv_obj_set_height(ui_Button18, 60);
    lv_obj_set_x(ui_Button18, 177);
    lv_obj_set_y(ui_Button18, -20);
    lv_obj_set_align(ui_Button18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label25 = lv_label_create(ui_Button18);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Configuración\n   de control\n     remoto");
    lv_obj_set_style_text_font(ui_Label25, &ui_font_Montserrat_14_Latin_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ControlDeBrillo = lv_slider_create(ui_Screen1);
    lv_slider_set_value(ui_ControlDeBrillo, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ControlDeBrillo) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_ControlDeBrillo, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(ui_ControlDeBrillo, 179);
    lv_obj_set_height(ui_ControlDeBrillo, 10);
    lv_obj_set_x(ui_ControlDeBrillo, 130);
    lv_obj_set_y(ui_ControlDeBrillo, -140);
    lv_obj_set_align(ui_ControlDeBrillo, LV_ALIGN_CENTER);


    ui_ImagenControlDeBrillo = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImagenControlDeBrillo, &ui_img_1566007221);
    lv_obj_set_width(ui_ImagenControlDeBrillo, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_ImagenControlDeBrillo, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_ImagenControlDeBrillo, 20);
    lv_obj_set_y(ui_ImagenControlDeBrillo, -140);
    lv_obj_set_align(ui_ImagenControlDeBrillo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImagenControlDeBrillo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImagenControlDeBrillo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button18, ui_event_Button18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ControlDeBrillo, ui_event_ControlDeBrillo, LV_EVENT_ALL, NULL);
    uic_ImagenControlDeBrillo = ui_ImagenControlDeBrillo;

}
