// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Proyecto_TFM_2

#include "ui.h"

void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label83 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label83, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label83, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label83, -86);
    lv_obj_set_y(ui_Label83, -139);
    lv_obj_set_align(ui_Label83, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label83, "Selecciona el archivo de configuración");
    lv_obj_set_style_text_font(ui_Label83, &ui_font_Montserrat_14_Latin_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Config4 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Config4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Config4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Config4, -10);
    lv_obj_set_y(ui_Config4, 0);
    lv_obj_set_align(ui_Config4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Config4, "Configuración 4");
    lv_obj_set_style_text_font(ui_Config4, &ui_font_Montserrat_14_Latin_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Config3 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Config3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Config3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Config3, -10);
    lv_obj_set_y(ui_Config3, -25);
    lv_obj_set_align(ui_Config3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Config3, "Configuración 3");
    lv_obj_set_style_text_font(ui_Config3, &ui_font_Montserrat_14_Latin_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Config2 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Config2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Config2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Config2, -10);
    lv_obj_set_y(ui_Config2, -50);
    lv_obj_set_align(ui_Config2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Config2, "Configuración 2");
    lv_obj_set_style_text_font(ui_Config2, &ui_font_Montserrat_14_Latin_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Config1 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Config1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Config1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Config1, -10);
    lv_obj_set_y(ui_Config1, -75);
    lv_obj_set_align(ui_Config1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Config1, "Configuración 1");
    lv_obj_set_style_text_font(ui_Config1, &ui_font_Montserrat_14_Latin_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveEEPROM = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_SaveEEPROM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveEEPROM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SaveEEPROM, 0);
    lv_obj_set_y(ui_SaveEEPROM, 50);
    lv_obj_set_align(ui_SaveEEPROM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SaveEEPROM, "Guardar configuración actual en EEPROM");
    lv_obj_set_style_text_font(ui_SaveEEPROM, &ui_font_Montserrat_14_Latin_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button20 = lv_btn_create(ui_Screen7);
    lv_obj_set_width(ui_Button20, 81);
    lv_obj_set_height(ui_Button20, 33);
    lv_obj_set_x(ui_Button20, 185);
    lv_obj_set_y(ui_Button20, -73);
    lv_obj_set_align(ui_Button20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button20, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button20, lv_color_hex(0x009112), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Button20);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -1);
    lv_obj_set_y(ui_Label12, 0);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Volver");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_Montserrat_14_Latin_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label92 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label92, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label92, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label92, 0);
    lv_obj_set_y(ui_Label92, 100);
    lv_obj_set_align(ui_Label92, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label92, "Configuración seleccionada");
    lv_obj_add_flag(ui_Label92, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Label92, lv_color_hex(0x14AF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label92, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label92, &ui_font_Montserrat_14_Latin_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Config4, ui_event_Config4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Config3, ui_event_Config3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Config2, ui_event_Config2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Config1, ui_event_Config1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SaveEEPROM, ui_event_SaveEEPROM, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button20, ui_event_Button20, LV_EVENT_ALL, NULL);

}
