// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Proyecto_TFM_2

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -165);
    lv_obj_set_y(ui_Label1, 145);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Rotor de cola");

    ui_Label3 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -167);
    lv_obj_set_y(ui_Label3, 123);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Motor principal");

    ui_RotorDeCola = lv_slider_create(ui_Screen2);
    lv_slider_set_range(ui_RotorDeCola, -100, 100);
    lv_slider_set_value(ui_RotorDeCola, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_RotorDeCola) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_RotorDeCola, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_RotorDeCola, 219);
    lv_obj_set_height(ui_RotorDeCola, 10);
    lv_obj_set_x(ui_RotorDeCola, 19);
    lv_obj_set_y(ui_RotorDeCola, 145);
    lv_obj_set_align(ui_RotorDeCola, LV_ALIGN_CENTER);


    ui_MotorPrincipal = lv_slider_create(ui_Screen2);
    lv_slider_set_range(ui_MotorPrincipal, -100, 100);
    lv_slider_set_value(ui_MotorPrincipal, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_MotorPrincipal) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_MotorPrincipal, 0,
                                                                                                   LV_ANIM_OFF);
    lv_obj_set_width(ui_MotorPrincipal, 219);
    lv_obj_set_height(ui_MotorPrincipal, 10);
    lv_obj_set_x(ui_MotorPrincipal, 19);
    lv_obj_set_y(ui_MotorPrincipal, 122);
    lv_obj_set_align(ui_MotorPrincipal, LV_ALIGN_CENTER);


    ui_EstructuraMotores = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_EstructuraMotores, &ui_img_1208125608);
    lv_obj_set_width(ui_EstructuraMotores, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_EstructuraMotores, LV_SIZE_CONTENT);    /// 44
    lv_obj_set_x(ui_EstructuraMotores, -47);
    lv_obj_set_y(ui_EstructuraMotores, -53);
    lv_obj_set_align(ui_EstructuraMotores, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EstructuraMotores, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_EstructuraMotores, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EstructuraPrincipal = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_EstructuraPrincipal, &ui_img_base_y_estructura_principal_150x150_png);
    lv_obj_set_width(ui_EstructuraPrincipal, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_EstructuraPrincipal, LV_SIZE_CONTENT);    /// 150
    lv_obj_set_x(ui_EstructuraPrincipal, -79);
    lv_obj_set_y(ui_EstructuraPrincipal, 3);
    lv_obj_set_align(ui_EstructuraPrincipal, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EstructuraPrincipal, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_EstructuraPrincipal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FlechaVerdeRecta = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_FlechaVerdeRecta, &ui_img_720150280);
    lv_obj_set_width(ui_FlechaVerdeRecta, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_FlechaVerdeRecta, LV_SIZE_CONTENT);    /// 57
    lv_obj_set_x(ui_FlechaVerdeRecta, 145);
    lv_obj_set_y(ui_FlechaVerdeRecta, -54);
    lv_obj_set_align(ui_FlechaVerdeRecta, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FlechaVerdeRecta, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_FlechaVerdeRecta, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FlechaVerdeRectaGirada = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_FlechaVerdeRectaGirada, &ui_img_flecha_verde_girada_png);
    lv_obj_set_width(ui_FlechaVerdeRectaGirada, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_FlechaVerdeRectaGirada, LV_SIZE_CONTENT);    /// 57
    lv_obj_set_x(ui_FlechaVerdeRectaGirada, 152);
    lv_obj_set_y(ui_FlechaVerdeRectaGirada, -52);
    lv_obj_set_align(ui_FlechaVerdeRectaGirada, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FlechaVerdeRectaGirada, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_FlechaVerdeRectaGirada, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FlechaVerdeCurva = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_FlechaVerdeCurva, &ui_img_flecha_verde_curvada_50x50_png);
    lv_obj_set_width(ui_FlechaVerdeCurva, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_FlechaVerdeCurva, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_FlechaVerdeCurva, -200);
    lv_obj_set_y(ui_FlechaVerdeCurva, 4);
    lv_obj_set_align(ui_FlechaVerdeCurva, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FlechaVerdeCurva, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_FlechaVerdeCurva, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FlechaVerdeCurvaGirada = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_FlechaVerdeCurvaGirada, &ui_img_flecha_verde_invertida_50x50_png);
    lv_obj_set_width(ui_FlechaVerdeCurvaGirada, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_FlechaVerdeCurvaGirada, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_FlechaVerdeCurvaGirada, -194);
    lv_obj_set_y(ui_FlechaVerdeCurvaGirada, 3);
    lv_obj_set_align(ui_FlechaVerdeCurvaGirada, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FlechaVerdeCurvaGirada, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_FlechaVerdeCurvaGirada, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button2, 64);
    lv_obj_set_height(ui_Button2, 30);
    lv_obj_set_x(ui_Button2, 199);
    lv_obj_set_y(ui_Button2, 21);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x009112), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Inicio");

    ui_Button7 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button7, 195);
    lv_obj_set_height(ui_Button7, 27);
    lv_obj_set_x(ui_Button7, -122);
    lv_obj_set_y(ui_Button7, -141);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Encoders/Modelo gráfico");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_Montserrat_14_Latin_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button8 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button8, 62);
    lv_obj_set_height(ui_Button8, 31);
    lv_obj_set_x(ui_Button8, 199);
    lv_obj_set_y(ui_Button8, -16);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Reset");

    ui_Panel1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel1, 157);
    lv_obj_set_height(ui_Panel1, 43);
    lv_obj_set_x(ui_Panel1, 154);
    lv_obj_set_y(ui_Panel1, -136);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_V_rotor_1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_V_rotor_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_V_rotor_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_V_rotor_1, -25);
    lv_obj_set_y(ui_V_rotor_1, -9);
    lv_obj_set_align(ui_V_rotor_1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_V_rotor_1, "V. rotor =");

    ui_V_motor_principal_1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_V_motor_principal_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_V_motor_principal_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_V_motor_principal_1, -20);
    lv_obj_set_y(ui_V_motor_principal_1, 9);
    lv_obj_set_align(ui_V_motor_principal_1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_V_motor_principal_1, "V. mp =");

    ui_GraphEncoder = lv_chart_create(ui_Screen2);
    lv_obj_set_width(ui_GraphEncoder, 278);
    lv_obj_set_height(ui_GraphEncoder, 181);
    lv_obj_set_x(ui_GraphEncoder, -50);
    lv_obj_set_y(ui_GraphEncoder, -17);
    lv_obj_set_align(ui_GraphEncoder, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GraphEncoder, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_chart_set_type(ui_GraphEncoder, LV_CHART_TYPE_LINE);

    lv_chart_set_point_count(ui_GraphEncoder, 300);
    lv_chart_set_update_mode(ui_GraphEncoder, LV_CHART_UPDATE_MODE_SHIFT);
    
    lv_chart_set_range(ui_GraphEncoder, LV_CHART_AXIS_PRIMARY_Y, -180, 180);
    lv_chart_set_range(ui_GraphEncoder, LV_CHART_AXIS_SECONDARY_Y, -180, 180);
    lv_chart_set_div_line_count(ui_GraphEncoder, 20, 5);
    lv_chart_set_axis_tick(ui_GraphEncoder, LV_CHART_AXIS_PRIMARY_X, 9, 3, 7, 7, true, 10);
    lv_chart_set_axis_tick(ui_GraphEncoder, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 7, 7, true, 50);
    lv_chart_set_axis_tick(ui_GraphEncoder, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 7, 7, true, 25);

    ui_GraphEncoder_series_1 = lv_chart_add_series(ui_GraphEncoder, lv_color_hex(0xFF0000),
                                               LV_CHART_AXIS_PRIMARY_Y);

    ui_GraphEncoder_series_2 = lv_chart_add_series(ui_GraphEncoder, lv_color_hex(0x2A00FF),
                                               LV_CHART_AXIS_SECONDARY_Y);




    /*
    lv_chart_series_t * ui_GraphEncoder_series_1 = lv_chart_add_series(ui_GraphEncoder, lv_color_hex(0xFF0000),
    LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_GraphEncoder_series_1_array[] = { 0 };
    lv_chart_set_ext_y_array(ui_GraphEncoder, ui_GraphEncoder_series_1, ui_GraphEncoder_series_1_array);
    lv_chart_series_t * ui_GraphEncoder_series_2 = lv_chart_add_series(ui_GraphEncoder, lv_color_hex(0x2A00FF),
                                                                       LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_GraphEncoder_series_2_array[] = { 0 };
    lv_chart_set_ext_y_array(ui_GraphEncoder, ui_GraphEncoder_series_2, ui_GraphEncoder_series_2_array);
    */


    ui_Panel2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel2, 100);
    lv_obj_set_height(ui_Panel2, 25);
    lv_obj_set_x(ui_Panel2, 39);
    lv_obj_set_y(ui_Panel2, -139);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_grad_color(ui_Panel2, lv_color_hex(0x850000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Rotor");

    ui_Panel3 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel3, 105);
    lv_obj_set_height(ui_Panel3, 25);
    lv_obj_set_x(ui_Panel3, 152);
    lv_obj_set_y(ui_Panel3, -139);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_grad_color(ui_Panel3, lv_color_hex(0x2E00FF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "M.principal");
    lv_obj_set_style_bg_grad_color(ui_Label14, lv_color_hex(0x3B00FF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label80 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label80, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label80, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label80, 25);
    lv_obj_set_y(ui_Label80, -135);
    lv_obj_set_align(ui_Label80, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label80, " Modo\nManual");

    ui_VinRDC = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_VinRDC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VinRDC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VinRDC, 175);
    lv_obj_set_y(ui_VinRDC, 142);
    lv_obj_set_align(ui_VinRDC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VinRDC, "Vin =");

    ui_VinMP = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_VinMP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VinMP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VinMP, 175);
    lv_obj_set_y(ui_VinMP, 121);
    lv_obj_set_align(ui_VinMP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VinMP, "Vin =");

    ui_Label43 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label43, 153);
    lv_obj_set_y(ui_Label43, -103);
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "Tacómetros");
    lv_obj_set_style_text_font(ui_Label43, &ui_font_Montserrat_14_Latin_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_RotorDeCola, ui_event_RotorDeCola, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MotorPrincipal, ui_event_MotorPrincipal, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);
    uic_Slider3 = ui_RotorDeCola;

}
