// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Proyecto_TFM_2

#include "ui.h"
#include "Navigation.h"
#include "General_Diagram.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button15 = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_Button15, 100);
    lv_obj_set_height(ui_Button15, 50);
    lv_obj_set_x(ui_Button15, 184);
    lv_obj_set_y(ui_Button15, -130);
    lv_obj_set_align(ui_Button15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button15, lv_color_hex(0x009112), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label58 = lv_label_create(ui_Button15);
    lv_obj_set_width(ui_Label58, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label58, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label58, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label58, "Volver");
    lv_obj_set_style_text_font(ui_Label58, &ui_font_Montserrat_14_Latin_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label59 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label59, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label59, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label59, -55);
    lv_obj_set_y(ui_Label59, -130);
    lv_obj_set_align(ui_Label59, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label59,
                      "Esquema completo de funcionamiento de TRMS\n\nPulsa en los bloques azules para ver su contenido");
    lv_obj_set_style_text_font(ui_Label59, &ui_font_Montserrat_14_Latin_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EsquemaTRMSCompleto = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_EsquemaTRMSCompleto, &ui_img_imagen_redimensionada_png);
    lv_obj_set_width(ui_EsquemaTRMSCompleto, LV_SIZE_CONTENT);   /// 445
    lv_obj_set_height(ui_EsquemaTRMSCompleto, LV_SIZE_CONTENT);    /// 242
    lv_obj_set_x(ui_EsquemaTRMSCompleto, -4);
    lv_obj_set_y(ui_EsquemaTRMSCompleto, 32);
    lv_obj_set_align(ui_EsquemaTRMSCompleto, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EsquemaTRMSCompleto, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_EsquemaTRMSCompleto, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EsquemaGeneral = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_EsquemaGeneral, &ui_img_esquema_general_redimensionado_png);
    lv_obj_set_width(ui_EsquemaGeneral, LV_SIZE_CONTENT);   /// 450
    lv_obj_set_height(ui_EsquemaGeneral, LV_SIZE_CONTENT);    /// 198
    lv_obj_set_x(ui_EsquemaGeneral, 2);
    lv_obj_set_y(ui_EsquemaGeneral, 28);
    lv_obj_set_align(ui_EsquemaGeneral, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EsquemaGeneral, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_EsquemaGeneral, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EsquemaPIDCompleto = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_EsquemaPIDCompleto, &ui_img_esquema_pid_completo_redimensionado_png);
    lv_obj_set_width(ui_EsquemaPIDCompleto, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_EsquemaPIDCompleto, LV_SIZE_CONTENT);    /// 229
    lv_obj_set_x(ui_EsquemaPIDCompleto, -5);
    lv_obj_set_y(ui_EsquemaPIDCompleto, 28);
    lv_obj_set_align(ui_EsquemaPIDCompleto, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EsquemaPIDCompleto, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_EsquemaPIDCompleto, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Label58, ui_event_Label58, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button15, ui_event_Button15, LV_EVENT_ALL, NULL);

    //Botones creados por mí para el esquema
    // Botón invisible para el bloque PID
    ui_BtnPIDZone = lv_btn_create(ui_EsquemaGeneral);
    lv_obj_set_pos(ui_BtnPIDZone, ESQ_PID_X1, ESQ_PID_Y1);
    lv_obj_set_size(ui_BtnPIDZone,
                    ESQ_PID_X2 - ESQ_PID_X1,
                    ESQ_PID_Y2 - ESQ_PID_Y1);
    lv_obj_set_style_bg_opa(ui_BtnPIDZone, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_opa(ui_BtnPIDZone, LV_OPA_TRANSP, 0);

    // Botón invisible para el bloque TRMS
    ui_BtnTRMSZone = lv_btn_create(ui_EsquemaGeneral);
    lv_obj_set_pos(ui_BtnTRMSZone, ESQ_TRMS_X1, ESQ_TRMS_Y1);
    lv_obj_set_size(ui_BtnTRMSZone,
                    ESQ_TRMS_X2 - ESQ_TRMS_X1,
                    ESQ_TRMS_Y2 - ESQ_TRMS_Y1);
    lv_obj_set_style_bg_opa(ui_BtnTRMSZone, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_opa(ui_BtnTRMSZone, LV_OPA_TRANSP, 0);

    // Eventos para pulsar con el dedo (por si quieres que el toque funcione igual)
    lv_obj_add_event_cb(ui_BtnPIDZone, [](lv_event_t * e) {
        if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
            GeneralDiagram_SelectPID();
        }
    }, LV_EVENT_ALL, nullptr);

    lv_obj_add_event_cb(ui_BtnTRMSZone, [](lv_event_t * e) {
        if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
            GeneralDiagram_SelectTRMS();
        }
    }, LV_EVENT_ALL, nullptr);

}
