// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen11_screen_init(void)
{
    ui_Screen11 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2y = lv_img_create(ui_Screen11);
    lv_img_set_src(ui_Image2y, &ui_img_1570174852);
    lv_obj_set_width(ui_Image2y, LV_SIZE_CONTENT);   /// 255
    lv_obj_set_height(ui_Image2y, LV_SIZE_CONTENT);    /// 194
    lv_obj_set_x(ui_Image2y, -110);
    lv_obj_set_y(ui_Image2y, -72);
    lv_obj_set_align(ui_Image2y, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2y, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2y, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3y = lv_img_create(ui_Screen11);
    lv_img_set_src(ui_Image3y, &ui_img_1016581827);
    lv_obj_set_width(ui_Image3y, LV_SIZE_CONTENT);   /// 249
    lv_obj_set_height(ui_Image3y, LV_SIZE_CONTENT);    /// 146
    lv_obj_set_x(ui_Image3y, -110);
    lv_obj_set_y(ui_Image3y, 100);
    lv_obj_set_align(ui_Image3y, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3y, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3y, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1y = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label1y, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1y, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1y, 125);
    lv_obj_set_y(ui_Label1y, -135);
    lv_obj_set_align(ui_Label1y, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1y, "Calibración de encoders");
    lv_obj_set_style_text_color(ui_Label1y, lv_color_hex(0x0D0EBF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1y, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1y, &ui_font_Montserrat_14_Latin_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2y = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label2y, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2y, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2y, 125);
    lv_obj_set_y(ui_Label2y, -70);
    lv_obj_set_align(ui_Label2y, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2y,
                      "Ponga el dispositivo en la\nposición indicada en las \nimágenes a la izquierda,\ny pulse el botón \"calibrar\"");
    lv_obj_set_style_text_align(ui_Label2y, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2y, &ui_font_Montserrat_14_Latin_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2y = lv_btn_create(ui_Screen11);
    lv_obj_set_width(ui_Button2y, 110);
    lv_obj_set_height(ui_Button2y, 40);
    lv_obj_set_x(ui_Button2y, 125);
    lv_obj_set_y(ui_Button2y, 70);
    lv_obj_set_align(ui_Button2y, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2y, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2y, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2y, lv_color_hex(0xBB0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2y, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3y = lv_label_create(ui_Button2y);
    lv_obj_set_width(ui_Label3y, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3y, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3y, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3y, "Calibrar");

    ui_Button3y = lv_btn_create(ui_Screen11);
    lv_obj_set_width(ui_Button3y, 110);
    lv_obj_set_height(ui_Button3y, 40);
    lv_obj_set_x(ui_Button3y, 125);
    lv_obj_set_y(ui_Button3y, 120);
    lv_obj_set_align(ui_Button3y, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3y, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3y, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3y, lv_color_hex(0x00961D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3y, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4y = lv_label_create(ui_Button3y);
    lv_obj_set_width(ui_Label4y, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4y, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4y, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4y, "Continuar");

    ui_Label5y = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label5y, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5y, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5y, 125);
    lv_obj_set_y(ui_Label5y, 0);
    lv_obj_set_align(ui_Label5y, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5y, "Calibración terminada");
    lv_obj_add_flag(ui_Label5y, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Label5y, lv_color_hex(0x00961D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5y, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5y, &ui_font_Montserrat_14_Latin_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button2y, ui_event_Button2y, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3y, ui_event_Button3y, LV_EVENT_ALL, NULL);

}
