// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Proyecto_TFM_2

#ifndef _PROYECTO_TFM_2_UI_H
#define _PROYECTO_TFM_2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void AnimationMotorAscendente_Animation(lv_obj_t * TargetObject, int delay);
void AnimationMotorDescendiente_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label2;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label5;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label11;
void ui_event_Button18(lv_event_t * e);
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Label25;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label16;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label17;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label18;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label19;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label15;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Kpvv;
extern lv_obj_t * ui_Kpvh;
extern lv_obj_t * ui_Kivv;
extern lv_obj_t * ui_Kivh;
extern lv_obj_t * ui_Kdvv;
extern lv_obj_t * ui_Kdvh;
extern lv_obj_t * ui_Kphv;
extern lv_obj_t * ui_Kihh;
extern lv_obj_t * ui_Kihv;
extern lv_obj_t * ui_Kphh;
extern lv_obj_t * ui_Isatvv;
extern lv_obj_t * ui_Kdhh;
extern lv_obj_t * ui_Kdhv;
extern lv_obj_t * ui_Uvmax;
extern lv_obj_t * ui_Isathh;
extern lv_obj_t * ui_Isathv;
extern lv_obj_t * ui_Isatvh;
extern lv_obj_t * ui_Uhmax;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label57;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Label20;
void ui_event_SliderKpvv(lv_event_t * e);
extern lv_obj_t * ui_SliderKpvv;
void ui_event_SliderKivv(lv_event_t * e);
extern lv_obj_t * ui_SliderKivv;
void ui_event_SliderKdvh(lv_event_t * e);
extern lv_obj_t * ui_SliderKdvh;
void ui_event_SliderKdvv(lv_event_t * e);
extern lv_obj_t * ui_SliderKdvv;
void ui_event_SliderKivh(lv_event_t * e);
extern lv_obj_t * ui_SliderKivh;
void ui_event_SliderKpvh(lv_event_t * e);
extern lv_obj_t * ui_SliderKpvh;
void ui_event_SliderKihv(lv_event_t * e);
extern lv_obj_t * ui_SliderKihv;
void ui_event_SliderKphv(lv_event_t * e);
extern lv_obj_t * ui_SliderKphv;
void ui_event_SliderKihh(lv_event_t * e);
extern lv_obj_t * ui_SliderKihh;
void ui_event_SliderKphh(lv_event_t * e);
extern lv_obj_t * ui_SliderKphh;
void ui_event_SliderKdhv(lv_event_t * e);
extern lv_obj_t * ui_SliderKdhv;
void ui_event_SliderKdhh(lv_event_t * e);
extern lv_obj_t * ui_SliderKdhh;
void ui_event_SliderIsatvv(lv_event_t * e);
extern lv_obj_t * ui_SliderIsatvv;
void ui_event_SliderIsatvh(lv_event_t * e);
extern lv_obj_t * ui_SliderIsatvh;
void ui_event_SliderIsathv(lv_event_t * e);
extern lv_obj_t * ui_SliderIsathv;
void ui_event_SliderIsathh(lv_event_t * e);
extern lv_obj_t * ui_SliderIsathh;
void ui_event_SliderUvmax(lv_event_t * e);
extern lv_obj_t * ui_SliderUvmax;
void ui_event_SliderUhmax(lv_event_t * e);
extern lv_obj_t * ui_SliderUhmax;
extern lv_obj_t * ui_Label82;
void ui_event_Button25(lv_event_t * e);
extern lv_obj_t * ui_Button25;
extern lv_obj_t * ui_Label34;
void ui_event_Button21(lv_event_t * e);
extern lv_obj_t * ui_Button21;
extern lv_obj_t * ui_Label38;
// CUSTOM VARIABLES

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
void ui_event_Label58(lv_event_t * e);
extern lv_obj_t * ui_Label58;
extern lv_obj_t * ui_Label59;
extern lv_obj_t * ui_EsquemaTRMSCompleto;
extern lv_obj_t * ui_EsquemaGeneral;
extern lv_obj_t * ui_EsquemaPIDCompleto;
// CUSTOM VARIABLES

// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
extern lv_obj_t * ui_Screen6;
void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Label61;
extern lv_obj_t * ui_Label64;
extern lv_obj_t * ui_Label65;
extern lv_obj_t * ui_V_rotor_2;
void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Label72;
extern lv_obj_t * ui_V_motor_principal_2;
extern lv_obj_t * ui_GraphEncoder3;
void ui_event_Button26(lv_event_t * e);
extern lv_obj_t * ui_Button26;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Image12;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label3;
void ui_event_RotorDeCola(lv_event_t * e);
extern lv_obj_t * ui_RotorDeCola;
void ui_event_MotorPrincipal(lv_event_t * e);
extern lv_obj_t * ui_MotorPrincipal;
extern lv_obj_t * ui_EstructuraMotores;
extern lv_obj_t * ui_EstructuraPrincipal;
extern lv_obj_t * ui_FlechaVerdeRecta;
extern lv_obj_t * ui_FlechaVerdeRectaGirada;
extern lv_obj_t * ui_FlechaVerdeCurva;
extern lv_obj_t * ui_FlechaVerdeCurvaGirada;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label4;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label10;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_V_rotor_1;
extern lv_obj_t * ui_V_motor_principal_1;
extern lv_obj_t * ui_GraphEncoder;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label80;
extern lv_obj_t * ui_VinRDC;
extern lv_obj_t * ui_VinMP;
extern lv_obj_t * ui_Label43;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Slider3;

// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Label83;
void ui_event_Config4(lv_event_t * e);
extern lv_obj_t * ui_Config4;
void ui_event_Config3(lv_event_t * e);
extern lv_obj_t * ui_Config3;
void ui_event_Config2(lv_event_t * e);
extern lv_obj_t * ui_Config2;
void ui_event_Config1(lv_event_t * e);
extern lv_obj_t * ui_Config1;
void ui_event_Config5(lv_event_t * e);
extern lv_obj_t * ui_Config5;
void ui_event_Button20(lv_event_t * e);
extern lv_obj_t * ui_Button20;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label92;
// CUSTOM VARIABLES

// SCREEN: ui_Screen8
void ui_Screen8_screen_init(void);
extern lv_obj_t * ui_Screen8;
extern lv_obj_t * ui_Label24;
void ui_event_Button22(lv_event_t * e);
extern lv_obj_t * ui_Button22;
extern lv_obj_t * ui_Label26;
void ui_event_Label30(lv_event_t * e);
extern lv_obj_t * ui_Label30;
void ui_event_Label31(lv_event_t * e);
extern lv_obj_t * ui_Label31;
void ui_event_Label32(lv_event_t * e);
extern lv_obj_t * ui_Label32;
void ui_event_Label33(lv_event_t * e);
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Button24;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label28;
// CUSTOM VARIABLES

// SCREEN: ui_Screen10
void ui_Screen10_screen_init(void);
void ui_event_Screen10(lv_event_t * e);
extern lv_obj_t * ui_Screen10;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Image6;
// CUSTOM VARIABLES

// SCREEN: ui_Screen9
void ui_Screen9_screen_init(void);
extern lv_obj_t * ui_Screen9;
extern lv_obj_t * ui_Label27;
void ui_event_Button23(lv_event_t * e);
extern lv_obj_t * ui_Button23;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_ButtonSelected;
void ui_event_Button19(lv_event_t * e);
extern lv_obj_t * ui_Button19;
extern lv_obj_t * ui_Label21;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_reposo_png);    // assets/Reposo.png
LV_IMG_DECLARE(ui_img_logo_ugr_redimensionado_png);    // assets/Logo_UGR_Redimensionado.png
LV_IMG_DECLARE(ui_img_logo_granasat_redimensionado_png);    // assets/Logo_Granasat_Redimensionado.png
LV_IMG_DECLARE(ui_img_tabla_311px_con_textos_png);    // assets/tabla_311px_con_textos.png
LV_IMG_DECLARE(ui_img_imagen_redimensionada_png);    // assets/imagen_redimensionada.png
LV_IMG_DECLARE(ui_img_esquema_general_redimensionado_png);    // assets/Esquema_General_Redimensionado.png
LV_IMG_DECLARE(ui_img_esquema_pid_completo_redimensionado_png);    // assets/Esquema_PID_Completo_Redimensionado.png
LV_IMG_DECLARE(ui_img_68877468);    // assets/Cuadrícula_Ejes_Redimensionada.png
LV_IMG_DECLARE(ui_img_1208125608);    // assets/Estrucutra móvil.png
LV_IMG_DECLARE(ui_img_base_y_estructura_principal_150x150_png);    // assets/Base_y_estructura_principal_150x150.png
LV_IMG_DECLARE(ui_img_720150280);    // assets/Flecha_Verde (2).png
LV_IMG_DECLARE(ui_img_flecha_verde_girada_png);    // assets/Flecha_Verde_Girada.png
LV_IMG_DECLARE(ui_img_flecha_verde_curvada_50x50_png);    // assets/flecha_verde_curvada_50x50.png
LV_IMG_DECLARE(ui_img_flecha_verde_invertida_50x50_png);    // assets/flecha_verde_invertida_50x50.png
LV_IMG_DECLARE(ui_img_logo_ugr_rojo_redimensionado_png);    // assets/Logo_UGR_Rojo_Redimensionado.png
LV_IMG_DECLARE(ui_img_mando_ir_redimensionado_png);    // assets/Mando_IR_redimensionado.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
