// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Proyecto_TFM_2

#include "ui.h"
#include "MotorControl.h"
#include "PID_Parameters.h"
#include "General_Diagram.h"
#include "SD_Control.h"
#include "ScreensaverState.h"
#include <SD.h>
#include "Navigation.h"
#include "Ang_Select.h"

extern PID_CURR g_pidCurr;
extern PID_MIN  g_pidMin;
extern PID_MAX  g_pidMax;

extern bool flag_Config_Message;

// Variables de registro globales
int Registro_MP = 0; // Registro para el voltaje del motor principal (vertical)
int Registro_RDC = 0; // Registro pata el voltaje del rotor de cola (horizontal)

// Flag para saber en qué modo estamos
static bool modo_encoder_grafico = false;   // false = modelo mecánico, true = gráfica
static bool Encoders_flag = false;

// Las señal de control del Buzzer está invertida debido a un transistor pull-up de control, previo a este
void BuzzerWrite(bool level) {    
    digitalWrite(Buzzer, !level);}


// -------------------------------------------------------------------
// Encendido/apagado de elementos
// -------------------------------------------------------------------
static void mostrar_modelo_mecanico(void) {
    // Mostrar imágenes mecánicas
    lv_obj_clear_flag(ui_EstructuraMotores,      LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_EstructuraPrincipal,    LV_OBJ_FLAG_HIDDEN);

	// Ocultar gráfica
    lv_obj_add_flag(ui_GraphEncoder, LV_OBJ_FLAG_HIDDEN);
}

static void mostrar_grafica_encoder(void) {
    // Ocultar imágenes mecánicas
    lv_obj_add_flag(ui_EstructuraMotores,      LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_EstructuraPrincipal,    LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_FlechaVerdeRecta,       LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_FlechaVerdeRectaGirada, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_FlechaVerdeCurva,       LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_FlechaVerdeCurvaGirada, LV_OBJ_FLAG_HIDDEN);

    // Mostrar gráfica
    lv_obj_clear_flag(ui_GraphEncoder, LV_OBJ_FLAG_HIDDEN);
}

// Guarda los tres bloques de parámetros en el fichero solicitado
static bool PID_SaveConfigToFile(const char *path)
{
    File f = SD.open(path, FILE_WRITE);
    if (!f) {
        Serial.print("ERROR abriendo fichero: ");
        Serial.println(path);
        return false;
    }

    f.println("# CONFIGURACION PID -----------------------");

    // ======================
    // BLOQUE MIN
    // ======================
    f.println("[PID_MIN]");
    f.printf("KpvvMin=%.6f\n", g_pidMin.KpvvMin);
    f.printf("KpvhMin=%.6f\n", g_pidMin.KpvhMin);
    f.printf("KivvMin=%.6f\n", g_pidMin.KivvMin);
    f.printf("KivhMin=%.6f\n", g_pidMin.KivhMin);
    f.printf("KdvvMin=%.6f\n", g_pidMin.KdvvMin);
    f.printf("KdvhMin=%.6f\n", g_pidMin.KdvhMin);
    f.printf("KphvMin=%.6f\n", g_pidMin.KphvMin);
    f.printf("KphhMin=%.6f\n", g_pidMin.KphhMin);
    f.printf("KihvMin=%.6f\n", g_pidMin.KihvMin);
    f.printf("KihhMin=%.6f\n", g_pidMin.KihhMin);
    f.printf("KdhvMin=%.6f\n", g_pidMin.KdhvMin);
    f.printf("KdhhMin=%.6f\n", g_pidMin.KdhhMin);
    f.printf("IsatvvMin=%.6f\n", g_pidMin.IsatvvMin);
    f.printf("IsatvhMin=%.6f\n", g_pidMin.IsatvhMin);
    f.printf("IsathvMin=%.6f\n", g_pidMin.IsathvMin);
    f.printf("IsathhMin=%.6f\n", g_pidMin.IsathhMin);
    f.printf("UvmaxMin=%.6f\n",  g_pidMin.UvmaxMin);
    f.printf("UhmaxMin=%.6f\n",  g_pidMin.UhmaxMin);
    f.println();

    // ======================
    // BLOQUE CURR
    // ======================
    f.println("[PID_CURR]");
    f.printf("KpvvCurr=%.6f\n", g_pidCurr.KpvvCurr);
    f.printf("KpvhCurr=%.6f\n", g_pidCurr.KpvhCurr);
    f.printf("KivvCurr=%.6f\n", g_pidCurr.KivvCurr);
    f.printf("KivhCurr=%.6f\n", g_pidCurr.KivhCurr);
    f.printf("KdvvCurr=%.6f\n", g_pidCurr.KdvvCurr);
    f.printf("KdvhCurr=%.6f\n", g_pidCurr.KdvhCurr);
    f.printf("KphvCurr=%.6f\n", g_pidCurr.KphvCurr);
    f.printf("KphhCurr=%.6f\n", g_pidCurr.KphhCurr);
    f.printf("KihvCurr=%.6f\n", g_pidCurr.KihvCurr);
    f.printf("KihhCurr=%.6f\n", g_pidCurr.KihhCurr);
    f.printf("KdhvCurr=%.6f\n", g_pidCurr.KdhvCurr);
    f.printf("KdhhCurr=%.6f\n", g_pidCurr.KdhhCurr);
    f.printf("IsatvvCurr=%.6f\n", g_pidCurr.IsatvvCurr);
    f.printf("IsatvhCurr=%.6f\n", g_pidCurr.IsatvhCurr);
    f.printf("IsathvCurr=%.6f\n", g_pidCurr.IsathvCurr);
    f.printf("IsathhCurr=%.6f\n", g_pidCurr.IsathhCurr);
    f.printf("UvmaxCurr=%.6f\n",  g_pidCurr.UvmaxCurr);
    f.printf("UhmaxCurr=%.6f\n",  g_pidCurr.UhmaxCurr);
    f.println();

    // ======================
    // BLOQUE MAX
    // ======================
    f.println("[PID_MAX]");
    f.printf("KpvvMax=%.6f\n", g_pidMax.KpvvMax);
    f.printf("KpvhMax=%.6f\n", g_pidMax.KpvhMax);
    f.printf("KivvMax=%.6f\n", g_pidMax.KivvMax);
    f.printf("KivhMax=%.6f\n", g_pidMax.KivhMax);
    f.printf("KdvvMax=%.6f\n", g_pidMax.KdvvMax);
    f.printf("KdvhMax=%.6f\n", g_pidMax.KdvhMax);
    f.printf("KphvMax=%.6f\n", g_pidMax.KphvMax);
    f.printf("KphhMax=%.6f\n", g_pidMax.KphhMax);
    f.printf("KihvMax=%.6f\n", g_pidMax.KihvMax);
    f.printf("KihhMax=%.6f\n", g_pidMax.KihhMax);
    f.printf("KdhvMax=%.6f\n", g_pidMax.KdhvMax);
    f.printf("KdhhMax=%.6f\n", g_pidMax.KdhhMax);
    f.printf("IsatvvMax=%.6f\n", g_pidMax.IsatvvMax);
    f.printf("IsatvhMax=%.6f\n", g_pidMax.IsatvhMax);
    f.printf("IsathvMax=%.6f\n", g_pidMax.IsathvMax);
    f.printf("IsathhMax=%.6f\n", g_pidMax.IsathhMax);
    f.printf("UvmaxMax=%.6f\n",  g_pidMax.UvmaxMax);
    f.printf("UhmaxMax=%.6f\n",  g_pidMax.UhmaxMax);
    f.println("-------------------------------------------");

    f.close();

    Serial.print("Configuración PID guardada correctamente en ");
    Serial.println(path);
    return true;
}


void Initiate_Modo_Manual(lv_event_t * e)
{
	SetupScreen2Nav();   
    AngSelect_ResetRefBoth();

    digitalWrite(LED,HIGH);
    BuzzerWrite(HIGH);    
    delay(500);
    digitalWrite(LED,LOW);
    BuzzerWrite(LOW);

}

void Initiate_Control_PID(lv_event_t * e)
{
	SetupScreen3Nav();
    Reset_Encoders_Registros();

    digitalWrite(LED,HIGH);
    BuzzerWrite(HIGH);    
    delay(500);
    digitalWrite(LED,LOW);
    BuzzerWrite(LOW);
}


void function_Program_Select(lv_event_t * e)
{
	SetupScreen8Nav();
}

void function_IR_Config(lv_event_t * e)
{
	SetupScreen9Nav();
}

void function_Init_1(lv_event_t * e)
{
	SetupScreen1Nav();
}

void function_PID_Parameters_Config(lv_event_t * e)
{
	SetupScreen4Nav();
}

void function_Load_Parameters_From_SD(lv_event_t * e)
{
	SetupScreen7Nav();
}

void function_Start_Control_PID(lv_event_t * e)
{
	SetupScreen6Nav();
}

void Reset_Encoders_Registros()
{
    lv_slider_set_value(ui_MotorPrincipal, 0, LV_ANIM_OFF);
    motor_girar_a(0);
    ocultar_flecha(ui_FlechaVerdeRecta);
    ocultar_flecha(ui_FlechaVerdeRectaGirada);
    Registro_MP = 0;

    lv_slider_set_value(ui_RotorDeCola, 0, LV_ANIM_OFF);
    motor_girar_a(0);
    ocultar_flecha(ui_FlechaVerdeCurva);
    ocultar_flecha(ui_FlechaVerdeCurvaGirada);
    Registro_RDC = 0;
    
    MotorControl_update(Registro_MP, Registro_RDC);
}


void function_Reset_Encoders_And_Registers(lv_event_t * e)
{
	(void)e;           // para evitar warning de parámetro no usado
    Reset_Encoders_Registros();
}

void function_General_Diagram_Model(lv_event_t * e)
{
	SetupScreen5Nav();
}

void function_Control_PID_Menu(lv_event_t * e)
{
	SetupScreen3Nav();
    _ui_screen_change(
        &ui_Screen3,
        LV_SCR_LOAD_ANIM_FADE_ON,
        500, 0,
        &ui_Screen3_screen_init
    );
}

void function_Predeterminate_parameters(lv_event_t * e)
{
	PID_LoadDefaults();
}

void function_Kpvv(lv_event_t * e)
{
    g_pidCurr.KpvvCurr = lv_slider_get_value(ui_SliderKpvv) / 10.0f;
    Serial.print("KpvvCurr = ");
    Serial.println(g_pidCurr.KpvvCurr, 3);
    PID_UpdateParamLabel(ui_Kpvv, g_pidMin.KpvvMin, g_pidCurr.KpvvCurr, g_pidMax.KpvvMax);
}

void function_Kpvh(lv_event_t * e)
{
    g_pidCurr.KpvhCurr = lv_slider_get_value(ui_SliderKpvh) / 10.0f;
    Serial.print("KpvhCurr = ");
    Serial.println(g_pidCurr.KpvhCurr, 3);
    PID_UpdateParamLabel(ui_Kpvh, g_pidMin.KpvhMin, g_pidCurr.KpvhCurr, g_pidMax.KpvhMax);
}

void function_Kivv(lv_event_t * e)
{
    g_pidCurr.KivvCurr = lv_slider_get_value(ui_SliderKivv) / 10.0f;
    Serial.print("KivvCurr = ");
    Serial.println(g_pidCurr.KivvCurr, 3);
    PID_UpdateParamLabel(ui_Kivv, g_pidMin.KivvMin, g_pidCurr.KivvCurr, g_pidMax.KivvMax);
}

void function_Kivh(lv_event_t * e)
{
    g_pidCurr.KivhCurr = lv_slider_get_value(ui_SliderKivh) / 10.0f;
    Serial.print("KivhCurr = ");
    Serial.println(g_pidCurr.KivhCurr, 3);
    PID_UpdateParamLabel(ui_Kivh, g_pidMin.KivhMin, g_pidCurr.KivhCurr, g_pidMax.KivhMax);
}

void function_Kdvv(lv_event_t * e)
{
    g_pidCurr.KdvvCurr = lv_slider_get_value(ui_SliderKdvv) / 10.0f;
    Serial.print("KdvvCurr = ");
    Serial.println(g_pidCurr.KdvvCurr, 3);
    PID_UpdateParamLabel(ui_Kdvv, g_pidMin.KdvvMin, g_pidCurr.KdvvCurr, g_pidMax.KdvvMax);
}

void function_Kdvh(lv_event_t * e)
{
    g_pidCurr.KdvhCurr = lv_slider_get_value(ui_SliderKdvh) / 10.0f;
    Serial.print("KdvhCurr = ");
    Serial.println(g_pidCurr.KdvhCurr, 3);
    PID_UpdateParamLabel(ui_Kdvh, g_pidMin.KdvhMin, g_pidCurr.KdvhCurr, g_pidMax.KdvhMax);
}

void function_Kphv(lv_event_t * e)
{
    g_pidCurr.KphvCurr = lv_slider_get_value(ui_SliderKphv) / 10.0f;
    Serial.print("KphvCurr = ");
    Serial.println(g_pidCurr.KphvCurr, 3);
    PID_UpdateParamLabel(ui_Kphv, g_pidMin.KphvMin, g_pidCurr.KphvCurr, g_pidMax.KphvMax);
}

void function_Kphh(lv_event_t * e)
{
    g_pidCurr.KphhCurr = lv_slider_get_value(ui_SliderKphh) / 10.0f;
    Serial.print("KphhCurr = ");
    Serial.println(g_pidCurr.KphhCurr, 3);
    PID_UpdateParamLabel(ui_Kphh, g_pidMin.KphhMin, g_pidCurr.KphhCurr, g_pidMax.KphhMax);
}

void function_Kihv(lv_event_t * e)
{
    g_pidCurr.KihvCurr = lv_slider_get_value(ui_SliderKihv) / 10.0f;
    Serial.print("KihvCurr = ");
    Serial.println(g_pidCurr.KihvCurr, 3);
    PID_UpdateParamLabel(ui_Kihv, g_pidMin.KihvMin, g_pidCurr.KihvCurr, g_pidMax.KihvMax);
}

void function_Kihh(lv_event_t * e)
{
    g_pidCurr.KihhCurr = lv_slider_get_value(ui_SliderKihh) / 10.0f;
    Serial.print("KihhCurr = ");
    Serial.println(g_pidCurr.KihhCurr, 3);
    PID_UpdateParamLabel(ui_Kihh, g_pidMin.KihhMin, g_pidCurr.KihhCurr, g_pidMax.KihhMax);
}

void function_Kdhv(lv_event_t * e)
{
    g_pidCurr.KdhvCurr = lv_slider_get_value(ui_SliderKdhv) / 10.0f;
    Serial.print("KdhvCurr = ");
    Serial.println(g_pidCurr.KdhvCurr, 3);
    PID_UpdateParamLabel(ui_Kdhv, g_pidMin.KdhvMin, g_pidCurr.KdhvCurr, g_pidMax.KdhvMax);
}

void function_Kdhh(lv_event_t * e)
{
    g_pidCurr.KdhhCurr = lv_slider_get_value(ui_SliderKdhh) / 10.0f;
    Serial.print("KdhhCurr = ");
    Serial.println(g_pidCurr.KdhhCurr, 3);
    PID_UpdateParamLabel(ui_Kdhh, g_pidMin.KdhhMin, g_pidCurr.KdhhCurr, g_pidMax.KdhhMax);
}

void function_Isatvv(lv_event_t * e)
{
    g_pidCurr.IsatvvCurr = lv_slider_get_value(ui_SliderIsatvv) / 10.0f;
    Serial.print("IsatvvCurr = ");
    Serial.println(g_pidCurr.IsatvvCurr, 3);
    PID_UpdateParamLabel(ui_Isatvv, g_pidMin.IsatvvMin, g_pidCurr.IsatvvCurr, g_pidMax.IsatvvMax);
}

void function_Isatvh(lv_event_t * e)
{
    g_pidCurr.IsatvhCurr = lv_slider_get_value(ui_SliderIsatvh) / 10.0f;
    Serial.print("IsatvhCurr = ");
    Serial.println(g_pidCurr.IsatvhCurr, 3);
    PID_UpdateParamLabel(ui_Isatvh, g_pidMin.IsatvhMin, g_pidCurr.IsatvhCurr, g_pidMax.IsatvhMax);
}

void function_Isathv(lv_event_t * e)
{
    g_pidCurr.IsathvCurr = lv_slider_get_value(ui_SliderIsathv) / 10.0f;
    Serial.print("IsathvCurr = ");
    Serial.println(g_pidCurr.IsathvCurr, 3);
    PID_UpdateParamLabel(ui_Isathv, g_pidMin.IsathvMin, g_pidCurr.IsathvCurr, g_pidMax.IsathvMax);
}

void function_Isathh(lv_event_t * e)
{
    g_pidCurr.IsathhCurr = lv_slider_get_value(ui_SliderIsathh) / 10.0f;
    Serial.print("IsathhCurr = ");
    Serial.println(g_pidCurr.IsathhCurr, 3);
    PID_UpdateParamLabel(ui_Isathh, g_pidMin.IsathhMin, g_pidCurr.IsathhCurr, g_pidMax.IsathhMax);
}

void function_Uvmax(lv_event_t * e)
{
    g_pidCurr.UvmaxCurr = lv_slider_get_value(ui_SliderUvmax) / 10.0f;
    Serial.print("UvmaxCurr = ");
    Serial.println(g_pidCurr.UvmaxCurr, 3);
    PID_UpdateParamLabel(ui_Uvmax, g_pidMin.UvmaxMin, g_pidCurr.UvmaxCurr, g_pidMax.UvmaxMax);
}

void function_Uhmax(lv_event_t * e)
{
    g_pidCurr.UhmaxCurr = lv_slider_get_value(ui_SliderUhmax) / 10.0f;
    Serial.print("UhmaxCurr = ");
    Serial.println(g_pidCurr.UhmaxCurr, 3);
    PID_UpdateParamLabel(ui_Uhmax, g_pidMin.UhmaxMin, g_pidCurr.UhmaxCurr, g_pidMax.UhmaxMax);
}

void function_Save_Config_1(lv_event_t * e)
{
	(void)e;
    PID_SaveConfigToFile("/Config_PID/Config_1.txt");
}

void function_Save_Config_2(lv_event_t * e)
{
	(void)e;
    PID_SaveConfigToFile("/Config_PID/Config_2.txt");
}

void function_Change_Images(lv_event_t * e)
{
    (void)e; // no usamos el evento

    // ¿Qué imagen está visible ahora?
    bool generalVisible = !lv_obj_has_flag(ui_EsquemaGeneral,      LV_OBJ_FLAG_HIDDEN);
    bool pidVisible     = !lv_obj_has_flag(ui_EsquemaPIDCompleto,  LV_OBJ_FLAG_HIDDEN);
    bool trmsVisible    = !lv_obj_has_flag(ui_EsquemaTRMSCompleto, LV_OBJ_FLAG_HIDDEN);

    // 1) Si el esquema general está visible → volver a Screen3

    if (generalVisible) {
        _ui_screen_change(
            &ui_Screen3,
            LV_SCR_LOAD_ANIM_FADE_ON,
            500, 0,
            &ui_Screen3_screen_init
        );

        SetupScreen3Nav();

        return; // después ya no se ejecuta nada más
    }


    // 2) Si está visible cualquiera de los otros dos → volver al esquema general
    if (pidVisible || trmsVisible) {
        lv_obj_add_flag(ui_EsquemaPIDCompleto,  LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_EsquemaTRMSCompleto, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_EsquemaGeneral,    LV_OBJ_FLAG_HIDDEN);
    }
}


void function_Control_PID_Menu_1(lv_event_t * e)
{
	SetupScreen3Nav();
}

void function_Encoders_2(lv_event_t * e)
{
    Encoders_flag = !Encoders_flag;

    if (Encoders_flag) {
        lv_obj_clear_flag(ui_GraphEncoder3, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_HIDDEN);
    } else {
        lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_GraphEncoder3, LV_OBJ_FLAG_HIDDEN);
    }
}


void Encoders_GraphicModel(lv_event_t * e)
{
	// Your code here
}

void F_Rotor_De_Cola(lv_event_t * e)
{
    Registro_RDC = lv_slider_get_value(ui_RotorDeCola);
	Serial.print("Slider -> Registro_RDC = ");
	Serial.println(Registro_RDC);
	MotorControl_update(Registro_MP, Registro_RDC);
}


void F_Motor_Principal(lv_event_t * e)
{
    Registro_MP = lv_slider_get_value(ui_MotorPrincipal);
	Serial.print("Slider -> Registro_MP = ");
	Serial.println(Registro_MP);
	MotorControl_update(Registro_MP, Registro_RDC);
	
}

void function_Init(lv_event_t * e)
{
	SetupScreen1Nav();
}

void function_Encoders_GraphModel(lv_event_t * e)
{
	LV_UNUSED(e);   // por si el compilador se queja de e sin usar

    // Cambiamos de modo
    modo_encoder_grafico = !modo_encoder_grafico;

    if (modo_encoder_grafico) {
        mostrar_grafica_encoder();
    } else {
        mostrar_modelo_mecanico();
    }
}

void Show_Config_Message_Selected(){
    delay(2500);
    lv_obj_add_flag(ui_Label92, LV_OBJ_FLAG_HIDDEN);
    flag_Config_Message = false;
}

void function_Load_Config_4(lv_event_t * e)
{
	(void)e;
    Serial.println("Config_4_Selected");
    lv_label_set_text(ui_Label92, "Configuracion 4 seleccionada");
    ControlSD_LoadConfig(4);
}

void function_Load_Config_3(lv_event_t * e)
{
	(void)e;
    Serial.println("Config_3_Selected");
    lv_label_set_text(ui_Label92, "Configuracion 3 seleccionada");
    ControlSD_LoadConfig(3);
}

void function_Load_Config_2(lv_event_t * e)
{
	(void)e;
    Serial.println("Config_2_Selected");
    lv_label_set_text(ui_Label92, "Configuracion 2 seleccionada");
    ControlSD_LoadConfig(2);
}

void function_Load_Config_1(lv_event_t * e)
{
	(void)e;
    Serial.println("Config_1_Selected");
    lv_label_set_text(ui_Label92, "Configuracion 1 seleccionada");
    ControlSD_LoadConfig(1);
}

void function_Save_Config_5_In_EEPROM(lv_event_t * e)
{
    (void)e;

    // Guardar g_pidCurr/g_pidMin/g_pidMax actuales en NVS
    PID_SaveToNVS();

    // Mostrar mensaje en la label 92
    lv_label_set_text(ui_Label92, "Configuración guardada en EEPROM");
    lv_obj_clear_flag(ui_Label92, LV_OBJ_FLAG_HIDDEN);
    flag_Config_Message = true;
}

void function_Control_PID_Menu_2(lv_event_t * e)
{
	SetupScreen3Nav();
}

void function_Init_2(lv_event_t * e)
{
	SetupScreen1Nav();
}

void function_Program_4(lv_event_t * e)
{
	// Your code here
}

void function_Program_3(lv_event_t * e)
{
	// Your code here
}

void function_Program_2(lv_event_t * e)
{
	// Your code here
}

void function_Program_1(lv_event_t * e)
{
	// Your code here
}

void function_Salvapantallas(lv_event_t * e)
{
    (void)e;  // para evitar warning de variable sin usar

    // Si no venimos del salvapantallas, no hacemos nada
    if (!g_screensaverActive) {
        return;
    }

    // Volver a la pantalla anterior según el flag
    switch (g_prevScreenId) {
        case SCR_1:
            SetupScreen1Nav();
            _ui_screen_change(
                &ui_Screen1,
                LV_SCR_LOAD_ANIM_FADE_ON,
                500, 0,
                &ui_Screen1_screen_init
            );
            break;

        case SCR_2:
            SetupScreen2Nav();
            _ui_screen_change(
                &ui_Screen2,
                LV_SCR_LOAD_ANIM_FADE_ON,
                500, 0,
                &ui_Screen2_screen_init
            );
            break;

        case SCR_3:
            SetupScreen3Nav();
            _ui_screen_change(
                &ui_Screen3,
                LV_SCR_LOAD_ANIM_FADE_ON,
                500, 0,
                &ui_Screen3_screen_init
            );
            break;

        case SCR_4:
            SetupScreen4Nav();
            _ui_screen_change(
                &ui_Screen4,
                LV_SCR_LOAD_ANIM_FADE_ON,
                500, 0,
                &ui_Screen4_screen_init
            );
            break;

        case SCR_5:
            SetupScreen5Nav();
            _ui_screen_change(
                &ui_Screen5,
                LV_SCR_LOAD_ANIM_FADE_ON,
                500, 0,
                &ui_Screen5_screen_init
            );
            break;

        case SCR_6:
            SetupScreen6Nav();
            _ui_screen_change(
                &ui_Screen6,
                LV_SCR_LOAD_ANIM_FADE_ON,
                500, 0,
                &ui_Screen6_screen_init
            );
            break;

        case SCR_7:
            SetupScreen7Nav();
            _ui_screen_change(
                &ui_Screen7,
                LV_SCR_LOAD_ANIM_FADE_ON,
                500, 0,
                &ui_Screen7_screen_init
            );
            break;

        case SCR_8:
            SetupScreen8Nav();
            _ui_screen_change(
                &ui_Screen8,
                LV_SCR_LOAD_ANIM_FADE_ON,
                500, 0,
                &ui_Screen8_screen_init
            );
            break;

        case SCR_9:
            SetupScreen9Nav();
            _ui_screen_change(
                &ui_Screen9,
                LV_SCR_LOAD_ANIM_FADE_ON,
                500, 0,
                &ui_Screen9_screen_init
            );
            break;    

        case SCR_NONE:
        default:
            // Si por alguna razón no sabemos de dónde venimos, volvemos a la patalla de inicio
            SetupScreen1Nav();
            _ui_screen_change(
                &ui_Screen1,
                LV_SCR_LOAD_ANIM_FADE_ON,
                500, 0,
                &ui_Screen1_screen_init
            );
            break;
    }

    // Limpiar estado de salvapantallas
    g_screensaverActive = false;
    g_prevScreenId      = SCR_NONE;
}

void function_Init_3(lv_event_t * e)
{
	SetupScreen1Nav();
}

void function_Angle_Reset(lv_event_t * e)
{
	AngSelect_ResetRefBoth();
}
void function_Save_Button_Config(lv_event_t * e)
{
    (void)e;
    IRControl_saveConfigToNVS();

    // opcional, mensaje en la label:
    lv_label_set_text(ui_ButtonSelected, "Configuracion guardada en EEPROM");
    lv_obj_clear_flag(ui_ButtonSelected, LV_OBJ_FLAG_HIDDEN);
}