// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Proyecto_TFM_2

#include "ui.h"
#include "Remote_Diagram.h"

void ui_Screen9_screen_init(void)
{
    ui_Screen9 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label27 = lv_label_create(ui_Screen9);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, -2);
    lv_obj_set_y(ui_Label27, -115);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27,
                      "Configuracion de mando de control remoto por infrarrojos\n\nSelecciona un boton en la imagen y luego el correspondiente \nen el mando IR que se quiera sincronizar");

    ui_Button23 = lv_btn_create(ui_Screen9);
    lv_obj_set_width(ui_Button23, 125);
    lv_obj_set_height(ui_Button23, 25);
    lv_obj_set_x(ui_Button23, 150);
    lv_obj_set_y(ui_Button23, 140);
    lv_obj_set_align(ui_Button23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button23, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label29 = lv_label_create(ui_Button23);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "Inicio");

    ui_Image7 = lv_img_create(ui_Screen9);
    lv_img_set_src(ui_Image7, &ui_img_mando_ir_redimensionado_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 421
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 150
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonSelected = lv_label_create(ui_Screen9);
    lv_obj_set_width(ui_ButtonSelected, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonSelected, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ButtonSelected, -90);
    lv_obj_set_y(ui_ButtonSelected, 120);
    lv_obj_set_align(ui_ButtonSelected, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonSelected, "Boton x seleccionado\nSincronizado con codigo del mando x");
    lv_obj_set_style_text_color(ui_ButtonSelected, lv_color_hex(0x14AF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ButtonSelected, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button19 = lv_btn_create(ui_Screen9);
    lv_obj_set_width(ui_Button19, 125);
    lv_obj_set_height(ui_Button19, 45);
    lv_obj_set_x(ui_Button19, 150);
    lv_obj_set_y(ui_Button19, 100);
    lv_obj_set_align(ui_Button19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button19, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label21 = lv_label_create(ui_Button19);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Guardar Config \n   en EEPROM");

    lv_obj_add_event_cb(ui_Button23, ui_event_Button23, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button19, ui_event_Button19, LV_EVENT_ALL, NULL);

    //Declaración como objetos secciones de la imagen agregada como argumento
    RemoteDiagram_Init(ui_Image7);

}
