// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Proyecto_TFM_2

#include "ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image5, &ui_img_tabla_311px_con_textos_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 198
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 311
    lv_obj_set_x(ui_Image5, -127);
    lv_obj_set_y(ui_Image5, -2);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Kpvv = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Kpvv, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Kpvv, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Kpvv, -88);
    lv_obj_set_y(ui_Kpvv, -131);
    lv_obj_set_align(ui_Kpvv, LV_ALIGN_CENTER);

    ui_Kpvh = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Kpvh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Kpvh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Kpvh, -88);
    lv_obj_set_y(ui_Kpvh, -115);
    lv_obj_set_align(ui_Kpvh, LV_ALIGN_CENTER);

    ui_Kivv = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Kivv, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Kivv, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Kivv, -88);
    lv_obj_set_y(ui_Kivv, -99);
    lv_obj_set_align(ui_Kivv, LV_ALIGN_CENTER);

    ui_Kivh = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Kivh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Kivh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Kivh, -88);
    lv_obj_set_y(ui_Kivh, -82);
    lv_obj_set_align(ui_Kivh, LV_ALIGN_CENTER);

    ui_Kdvv = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Kdvv, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Kdvv, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Kdvv, -88);
    lv_obj_set_y(ui_Kdvv, -67);
    lv_obj_set_align(ui_Kdvv, LV_ALIGN_CENTER);

    ui_Kdvh = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Kdvh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Kdvh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Kdvh, -88);
    lv_obj_set_y(ui_Kdvh, -51);
    lv_obj_set_align(ui_Kdvh, LV_ALIGN_CENTER);

    ui_Kphv = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Kphv, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Kphv, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Kphv, -88);
    lv_obj_set_y(ui_Kphv, -34);
    lv_obj_set_align(ui_Kphv, LV_ALIGN_CENTER);

    ui_Kihh = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Kihh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Kihh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Kihh, -88);
    lv_obj_set_y(ui_Kihh, 16);
    lv_obj_set_align(ui_Kihh, LV_ALIGN_CENTER);

    ui_Kihv = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Kihv, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Kihv, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Kihv, -88);
    lv_obj_set_y(ui_Kihv, 0);
    lv_obj_set_align(ui_Kihv, LV_ALIGN_CENTER);

    ui_Kphh = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Kphh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Kphh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Kphh, -88);
    lv_obj_set_y(ui_Kphh, -17);
    lv_obj_set_align(ui_Kphh, LV_ALIGN_CENTER);

    ui_Isatvv = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Isatvv, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Isatvv, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Isatvv, -88);
    lv_obj_set_y(ui_Isatvv, 65);
    lv_obj_set_align(ui_Isatvv, LV_ALIGN_CENTER);

    ui_Kdhh = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Kdhh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Kdhh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Kdhh, -88);
    lv_obj_set_y(ui_Kdhh, 49);
    lv_obj_set_align(ui_Kdhh, LV_ALIGN_CENTER);

    ui_Kdhv = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Kdhv, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Kdhv, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Kdhv, -88);
    lv_obj_set_y(ui_Kdhv, 32);
    lv_obj_set_align(ui_Kdhv, LV_ALIGN_CENTER);

    ui_Uvmax = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Uvmax, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Uvmax, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Uvmax, -88);
    lv_obj_set_y(ui_Uvmax, 130);
    lv_obj_set_align(ui_Uvmax, LV_ALIGN_CENTER);

    ui_Isathh = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Isathh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Isathh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Isathh, -88);
    lv_obj_set_y(ui_Isathh, 114);
    lv_obj_set_align(ui_Isathh, LV_ALIGN_CENTER);

    ui_Isathv = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Isathv, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Isathv, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Isathv, -88);
    lv_obj_set_y(ui_Isathv, 97);
    lv_obj_set_align(ui_Isathv, LV_ALIGN_CENTER);

    ui_Isatvh = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Isatvh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Isatvh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Isatvh, -88);
    lv_obj_set_y(ui_Isatvh, 81);
    lv_obj_set_align(ui_Isatvh, LV_ALIGN_CENTER);

    ui_Uhmax = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Uhmax, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Uhmax, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Uhmax, -88);
    lv_obj_set_y(ui_Uhmax, 146);
    lv_obj_set_align(ui_Uhmax, LV_ALIGN_CENTER);

    ui_Button13 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button13, 86);
    lv_obj_set_height(ui_Button13, 50);
    lv_obj_set_x(ui_Button13, 193);
    lv_obj_set_y(ui_Button13, 131);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label57 = lv_label_create(ui_Button13);
    lv_obj_set_width(ui_Label57, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label57, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label57, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label57, "Volver");

    ui_Button14 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button14, 239);
    lv_obj_set_height(ui_Button14, 18);
    lv_obj_set_x(ui_Button14, 115);
    lv_obj_set_y(ui_Button14, -150);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_Button14);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Parametros predeterminados");

    ui_SliderKpvv = lv_slider_create(ui_Screen4);
    lv_slider_set_value(ui_SliderKpvv, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderKpvv) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderKpvv, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderKpvv, 150);
    lv_obj_set_height(ui_SliderKpvv, 5);
    lv_obj_set_x(ui_SliderKpvv, 62);
    lv_obj_set_y(ui_SliderKpvv, -132);
    lv_obj_set_align(ui_SliderKpvv, LV_ALIGN_CENTER);


    ui_SliderKivv = lv_slider_create(ui_Screen4);
    lv_slider_set_value(ui_SliderKivv, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderKivv) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderKivv, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderKivv, 150);
    lv_obj_set_height(ui_SliderKivv, 5);
    lv_obj_set_x(ui_SliderKivv, 62);
    lv_obj_set_y(ui_SliderKivv, -99);
    lv_obj_set_align(ui_SliderKivv, LV_ALIGN_CENTER);


    ui_SliderKdvh = lv_slider_create(ui_Screen4);
    lv_slider_set_value(ui_SliderKdvh, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderKdvh) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderKdvh, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderKdvh, 150);
    lv_obj_set_height(ui_SliderKdvh, 5);
    lv_obj_set_x(ui_SliderKdvh, 62);
    lv_obj_set_y(ui_SliderKdvh, -49);
    lv_obj_set_align(ui_SliderKdvh, LV_ALIGN_CENTER);


    ui_SliderKdvv = lv_slider_create(ui_Screen4);
    lv_slider_set_value(ui_SliderKdvv, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderKdvv) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderKdvv, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderKdvv, 150);
    lv_obj_set_height(ui_SliderKdvv, 5);
    lv_obj_set_x(ui_SliderKdvv, 62);
    lv_obj_set_y(ui_SliderKdvv, -66);
    lv_obj_set_align(ui_SliderKdvv, LV_ALIGN_CENTER);


    ui_SliderKivh = lv_slider_create(ui_Screen4);
    lv_slider_set_value(ui_SliderKivh, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderKivh) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderKivh, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderKivh, 150);
    lv_obj_set_height(ui_SliderKivh, 5);
    lv_obj_set_x(ui_SliderKivh, 62);
    lv_obj_set_y(ui_SliderKivh, -83);
    lv_obj_set_align(ui_SliderKivh, LV_ALIGN_CENTER);


    ui_SliderKpvh = lv_slider_create(ui_Screen4);
    lv_slider_set_value(ui_SliderKpvh, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderKpvh) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderKpvh, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderKpvh, 150);
    lv_obj_set_height(ui_SliderKpvh, 5);
    lv_obj_set_x(ui_SliderKpvh, 62);
    lv_obj_set_y(ui_SliderKpvh, -115);
    lv_obj_set_align(ui_SliderKpvh, LV_ALIGN_CENTER);


    ui_SliderKihv = lv_slider_create(ui_Screen4);
    lv_slider_set_value(ui_SliderKihv, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderKihv) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderKihv, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderKihv, 150);
    lv_obj_set_height(ui_SliderKihv, 5);
    lv_obj_set_x(ui_SliderKihv, 62);
    lv_obj_set_y(ui_SliderKihv, 0);
    lv_obj_set_align(ui_SliderKihv, LV_ALIGN_CENTER);


    ui_SliderKphv = lv_slider_create(ui_Screen4);
    lv_slider_set_value(ui_SliderKphv, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderKphv) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderKphv, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderKphv, 150);
    lv_obj_set_height(ui_SliderKphv, 5);
    lv_obj_set_x(ui_SliderKphv, 62);
    lv_obj_set_y(ui_SliderKphv, -33);
    lv_obj_set_align(ui_SliderKphv, LV_ALIGN_CENTER);


    ui_SliderKihh = lv_slider_create(ui_Screen4);
    lv_slider_set_value(ui_SliderKihh, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderKihh) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderKihh, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderKihh, 150);
    lv_obj_set_height(ui_SliderKihh, 5);
    lv_obj_set_x(ui_SliderKihh, 62);
    lv_obj_set_y(ui_SliderKihh, 16);
    lv_obj_set_align(ui_SliderKihh, LV_ALIGN_CENTER);


    ui_SliderKphh = lv_slider_create(ui_Screen4);
    lv_slider_set_value(ui_SliderKphh, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderKphh) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderKphh, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderKphh, 150);
    lv_obj_set_height(ui_SliderKphh, 5);
    lv_obj_set_x(ui_SliderKphh, 62);
    lv_obj_set_y(ui_SliderKphh, -16);
    lv_obj_set_align(ui_SliderKphh, LV_ALIGN_CENTER);


    ui_SliderKdhv = lv_slider_create(ui_Screen4);
    lv_slider_set_value(ui_SliderKdhv, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderKdhv) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderKdhv, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderKdhv, 150);
    lv_obj_set_height(ui_SliderKdhv, 5);
    lv_obj_set_x(ui_SliderKdhv, 62);
    lv_obj_set_y(ui_SliderKdhv, 32);
    lv_obj_set_align(ui_SliderKdhv, LV_ALIGN_CENTER);


    ui_SliderKdhh = lv_slider_create(ui_Screen4);
    lv_slider_set_value(ui_SliderKdhh, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderKdhh) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderKdhh, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderKdhh, 150);
    lv_obj_set_height(ui_SliderKdhh, 5);
    lv_obj_set_x(ui_SliderKdhh, 62);
    lv_obj_set_y(ui_SliderKdhh, 48);
    lv_obj_set_align(ui_SliderKdhh, LV_ALIGN_CENTER);


    ui_SliderIsatvv = lv_slider_create(ui_Screen4);
    lv_slider_set_value(ui_SliderIsatvv, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderIsatvv) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderIsatvv, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderIsatvv, 150);
    lv_obj_set_height(ui_SliderIsatvv, 5);
    lv_obj_set_x(ui_SliderIsatvv, 62);
    lv_obj_set_y(ui_SliderIsatvv, 64);
    lv_obj_set_align(ui_SliderIsatvv, LV_ALIGN_CENTER);


    ui_SliderIsatvh = lv_slider_create(ui_Screen4);
    lv_slider_set_value(ui_SliderIsatvh, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderIsatvh) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderIsatvh, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderIsatvh, 150);
    lv_obj_set_height(ui_SliderIsatvh, 5);
    lv_obj_set_x(ui_SliderIsatvh, 62);
    lv_obj_set_y(ui_SliderIsatvh, 80);
    lv_obj_set_align(ui_SliderIsatvh, LV_ALIGN_CENTER);


    ui_SliderIsathv = lv_slider_create(ui_Screen4);
    lv_slider_set_value(ui_SliderIsathv, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderIsathv) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderIsathv, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderIsathv, 150);
    lv_obj_set_height(ui_SliderIsathv, 5);
    lv_obj_set_x(ui_SliderIsathv, 62);
    lv_obj_set_y(ui_SliderIsathv, 96);
    lv_obj_set_align(ui_SliderIsathv, LV_ALIGN_CENTER);


    ui_SliderIsathh = lv_slider_create(ui_Screen4);
    lv_slider_set_value(ui_SliderIsathh, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderIsathh) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderIsathh, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderIsathh, 150);
    lv_obj_set_height(ui_SliderIsathh, 5);
    lv_obj_set_x(ui_SliderIsathh, 62);
    lv_obj_set_y(ui_SliderIsathh, 112);
    lv_obj_set_align(ui_SliderIsathh, LV_ALIGN_CENTER);


    ui_SliderUvmax = lv_slider_create(ui_Screen4);
    lv_slider_set_value(ui_SliderUvmax, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderUvmax) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderUvmax, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderUvmax, 150);
    lv_obj_set_height(ui_SliderUvmax, 5);
    lv_obj_set_x(ui_SliderUvmax, 62);
    lv_obj_set_y(ui_SliderUvmax, 129);
    lv_obj_set_align(ui_SliderUvmax, LV_ALIGN_CENTER);


    ui_SliderUhmax = lv_slider_create(ui_Screen4);
    lv_slider_set_value(ui_SliderUhmax, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderUhmax) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderUhmax, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderUhmax, 150);
    lv_obj_set_height(ui_SliderUhmax, 5);
    lv_obj_set_x(ui_SliderUhmax, 62);
    lv_obj_set_y(ui_SliderUhmax, 145);
    lv_obj_set_align(ui_SliderUhmax, LV_ALIGN_CENTER);


    ui_Label82 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label82, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label82, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label82, 191);
    lv_obj_set_y(ui_Label82, -107);
    lv_obj_set_align(ui_Label82, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label82, " Seleccion\n        de\nparametros");

    ui_Button25 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button25, 76);
    lv_obj_set_height(ui_Button25, 61);
    lv_obj_set_x(ui_Button25, 191);
    lv_obj_set_y(ui_Button25, -32);
    lv_obj_set_align(ui_Button25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button25, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label34 = lv_label_create(ui_Button25);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "Guardar\n     en\n Config 1");

    ui_Button21 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button21, 76);
    lv_obj_set_height(ui_Button21, 61);
    lv_obj_set_x(ui_Button21, 191);
    lv_obj_set_y(ui_Button21, 39);
    lv_obj_set_align(ui_Button21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button21, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label38 = lv_label_create(ui_Button21);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "Guardar\n     en\n Config 2");

    lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button14, ui_event_Button14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderKpvv, ui_event_SliderKpvv, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderKivv, ui_event_SliderKivv, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderKdvh, ui_event_SliderKdvh, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderKdvv, ui_event_SliderKdvv, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderKivh, ui_event_SliderKivh, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderKpvh, ui_event_SliderKpvh, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderKihv, ui_event_SliderKihv, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderKphv, ui_event_SliderKphv, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderKihh, ui_event_SliderKihh, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderKphh, ui_event_SliderKphh, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderKdhv, ui_event_SliderKdhv, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderKdhh, ui_event_SliderKdhh, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderIsatvv, ui_event_SliderIsatvv, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderIsatvh, ui_event_SliderIsatvh, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderIsathv, ui_event_SliderIsathv, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderIsathh, ui_event_SliderIsathh, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderUvmax, ui_event_SliderUvmax, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderUhmax, ui_event_SliderUhmax, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button25, ui_event_Button25, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button21, ui_event_Button21, LV_EVENT_ALL, NULL);

}
