// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Proyecto_TFM_2

#include "ui.h"

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button17 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Button17, 71);
    lv_obj_set_height(ui_Button17, 29);
    lv_obj_set_x(ui_Button17, 195);
    lv_obj_set_y(ui_Button17, 138);
    lv_obj_set_align(ui_Button17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button17, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label61 = lv_label_create(ui_Button17);
    lv_obj_set_width(ui_Label61, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label61, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label61, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label61, "Volver");

    ui_Label64 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label64, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label64, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label64, 147);
    lv_obj_set_y(ui_Label64, -125);
    lv_obj_set_align(ui_Label64, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label64, "A. vertical =");

    ui_Label65 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label65, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label65, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label65, 157);
    lv_obj_set_y(ui_Label65, -105);
    lv_obj_set_align(ui_Label65, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label65, "A. horizontal =");

    ui_V_rotor_2 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_V_rotor_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_V_rotor_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_V_rotor_2, 150);
    lv_obj_set_y(ui_V_rotor_2, -80);
    lv_obj_set_align(ui_V_rotor_2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_V_rotor_2, "V. rotor =");

    ui_Button16 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Button16, 105);
    lv_obj_set_height(ui_Button16, 45);
    lv_obj_set_x(ui_Button16, 160);
    lv_obj_set_y(ui_Button16, 60);
    lv_obj_set_align(ui_Button16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label72 = lv_label_create(ui_Button16);
    lv_obj_set_width(ui_Label72, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label72, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label72, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label72, "Encoders");

    ui_V_motor_principal_2 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_V_motor_principal_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_V_motor_principal_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_V_motor_principal_2, 150);
    lv_obj_set_y(ui_V_motor_principal_2, -60);
    lv_obj_set_align(ui_V_motor_principal_2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_V_motor_principal_2, "V. mp =");

    ui_GraphEncoder3 = lv_chart_create(ui_Screen6);
    lv_obj_set_width(ui_GraphEncoder3, 278);
    lv_obj_set_height(ui_GraphEncoder3, 181);
    lv_obj_set_x(ui_GraphEncoder3, -56);
    lv_obj_set_y(ui_GraphEncoder3, 33);
    lv_obj_set_align(ui_GraphEncoder3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GraphEncoder3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_chart_set_type(ui_GraphEncoder3, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_GraphEncoder3, 2401);
    lv_chart_set_range(ui_GraphEncoder3, LV_CHART_AXIS_PRIMARY_Y, -180, 180);
    lv_chart_set_range(ui_GraphEncoder3, LV_CHART_AXIS_SECONDARY_Y, -180, 180);
    lv_chart_set_div_line_count(ui_GraphEncoder3, 20, 5);
    lv_chart_set_axis_tick(ui_GraphEncoder3, LV_CHART_AXIS_PRIMARY_X, 9, 3, 7, 7, true, 10);
    lv_chart_set_axis_tick(ui_GraphEncoder3, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 7, 7, true, 50);
    lv_chart_set_axis_tick(ui_GraphEncoder3, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 7, 7, true, 25);
    lv_chart_series_t * ui_GraphEncoder3_series_1 = lv_chart_add_series(ui_GraphEncoder3, lv_color_hex(0xFF0000),
                                                                        LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_GraphEncoder3_series_1_array[] = { 0 };
    lv_chart_set_ext_y_array(ui_GraphEncoder3, ui_GraphEncoder3_series_1, ui_GraphEncoder3_series_1_array);
    lv_chart_series_t * ui_GraphEncoder3_series_2 = lv_chart_add_series(ui_GraphEncoder3, lv_color_hex(0x2A00FF),
                                                                        LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_GraphEncoder3_series_2_array[] = { 0 };
    lv_chart_set_ext_y_array(ui_GraphEncoder3, ui_GraphEncoder3_series_2, ui_GraphEncoder3_series_2_array);



    ui_Button26 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Button26, 105);
    lv_obj_set_height(ui_Button26, 45);
    lv_obj_set_x(ui_Button26, 160);
    lv_obj_set_y(ui_Button26, 10);
    lv_obj_set_align(ui_Button26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button26, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label39 = lv_label_create(ui_Button26);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "Reset");

    ui_Image12 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image12, &ui_img_68877468);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 309
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 309
    lv_obj_set_x(ui_Image12, -80);
    lv_obj_set_y(ui_Image12, 1);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button17, ui_event_Button17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button16, ui_event_Button16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button26, ui_event_Button26, LV_EVENT_ALL, NULL);

}
